title: Vong Yang # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>4  years of repairing and building computer and network equipment. 2 years of providing IT support.<br>
  Second description 
  <br>I am looking to become a Jr Web developer<br>
  <a href="https://www.linkedin.com/in/vong-y-1943a263/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
